opennaslab/kubespider

.github/pull-request-template.md, .github/workflows/kubespider-deploy-test.yaml, .github/workflows/kubespider-style.yaml, README.md, hack/install.sh, hack/install_baidunetdisk.sh, hack/install_plex.sh, hack/install_thunder.sh, kubespider/app.py, kubespider/core/download_trigger.py, kubespider/core/kubespider.py, kubespider/core/period_server.py, kubespider/core/webhook_server.py, kubespider/download_provider/aria2_download_provider/provider.py, kubespider/download_provider/provider.py, kubespider/source_provider/btbtt12_disposable_source_provider/provider.py, kubespider/source_provider/meijutt_source_provider/provider.py, kubespider/source_provider/mikanani_source_provider/provider.py, kubespider/source_provider/provider.py, kubespider/utils/helper.py, setup.py
Fixes #none
* Add deploy ci workflow
```release-note
```
=> Add deploy ci workflow

.github/workflows/kubespider-latest-build.yaml, .github/workflows/kubespider-style.yaml, .pylintrc, kubespider/core/download_trigger.py, kubespider/core/kubespider.py, kubespider/core/kubespider_global.py, kubespider/core/period_server.py, kubespider/core/webhook_server.py, kubespider/source_provider/mikanani_source_provider/provider.py
Fixes #none
* Fix code style and add latest release workflow
```release-note
```
=> Fix code style and add latest release workflow

chrome-extension/manifest.json, chrome-extension/service_worker.js
Fixes #none
* Add chrome context menue
```release-note
```
=> Add chrome context menue

.github/workflows/kubespider-style.yaml, README-CN.md, README.md, docs/zh/contribute/implement_source_provider_cn.md
Fixes #
* Add english readme and how to develop source provider
```release-note
```
=> Add english readme and how to develop source provider

chrome-extension/kubespider.js, chrome-extension/service_worker.js
Fixes #none
* Fix chrome context and do post with fetch
```release-note
```
=> Fix chrome context and do post with fetch

kubespider/source_provider/provider.py
Fixes #
* Fix meijutt source provider
```release-note
```
=> Fix meijutt source provider

.github/workflows/kubespider-release.yaml
Fixes #
*
*
*
```release-note
```
=> Fix release workflow

.github/workflows/kubespider-release.yaml
Fixes #
*
*
*
```release-note
```
=> Not attach script

README-CN.md, README.md
Fixes #
*
*
*
```release-note
```
=> Add link for dockerhub in readme

README.md
Fixes #
*
*
*
```release-note
```
=> Fix gramer

README-CN.md, README.md, docs/zh/roadmap.md
Fixes #
* Add more feature to roadmap
```release-note
```
=> Add more feature to roadmap

.kubespider/download_provider.cfg, .kubespider/source_provider.cfg, docs/zh/roadmap.md, docs/zh/user_guide/btbtt12_disposable_source_provider/README.md, docs/zh/user_guide/meijutt_source_provider/README.md, docs/zh/user_guide/mikanani_source_provider/README.md, kubespider/core/period_server.py, kubespider/download_provider/aria2_download_provider/provider.py, kubespider/download_provider/provider.py, kubespider/source_provider/btbtt12_disposable_source_provider/provider.py, kubespider/source_provider/meijutt_source_provider/provider.py, kubespider/source_provider/mikanani_source_provider/provider.py, kubespider/source_provider/provider.py, kubespider/utils/helper.py
Fixes #
* Make all config in json format
```release-note
```
=> Make all config in json format

README-CN.md, docs/zh/user_guide/thunder_install_config/README.md
Fixes #
*
*
*
```release-note
```
=> Update chinese docs

README-CN.md
Fixes #
*
*
*
```release-note
```
=> Fix docs link error

README-CN.md, README.md, docs/zh/roadmap.md, kubespider/core/webhook_server.py
Fixes #
* Fix torrent parse
*
*
```release-note
```
=> Fix torrent parse

CONTRIBUTING-CN.md, CONTRIBUTING.md, README-CN.md, README.md, docs/zh/roadmap.md
Fixes #
*
*
*
```release-note
```
=> Add docs how to develop

README-CN.md, README.md, chrome-extension/js/kubespider.js, chrome-extension/service_worker.js, docs/zh/roadmap.md, docs/zh/user_guide/api_docs/README.md, kubespider/app.py, kubespider/core/kubespider.py, kubespider/core/webhook_server.py, requirements.txt
Fixes #none
* Define standard apis
```release-note
```
=> Define standard apis

README-CN.md, docs/zh/user_guide/api_docs/README.md
Fixes #
*
*
*
```release-note
```
=> Fix docs typo

docs/zh/user_guide/aria2_download_provider/README.md
Fixes #
*
*
*
```release-note
```
=> Fix doc typo

README.md, docs/zh/roadmap.md, docs/zh/user_guide/api_docs/README.md
Fixes #
*
*
*
```release-note
```
=> Add api docs content

kubespider/core/download_trigger.py, kubespider/core/kubespider.py, kubespider/core/period_server.py, kubespider/source_provider/bilibili_source_provider/provider.py, kubespider/source_provider/btbtt12_disposable_source_provider/provider.py, kubespider/source_provider/meijutt_source_provider/provider.py, kubespider/source_provider/mikanani_source_provider/provider.py, kubespider/source_provider/provider.py, kubespider/utils/helper.py
Fixes #
* Refactor code and make it more clear
```release-note
```
=> Refactor code and make it more clear

README-CN.md, README.md
Fixes #
* Add python version support
*
*
```release-note
```
=> Add python version support

kubespider/core/period_server.py, kubespider/download_provider/aria2_download_provider/provider.py, kubespider/download_provider/provider.py, kubespider/download_provider/qbittorrent_download_provider/provider.py, kubespider/download_provider/xunlei_download_provider/provider.py
Fixes #
*
*
*
```release-note
```
=> Make code better

.config/download_provider.cfg, README-CN.md, README.md, docs/zh/roadmap.md, downloaders/you-get/Dockerfile, downloaders/you-get/README.md, downloaders/you-get/app/app.py, downloaders/you-get/app/core/tasks.py, downloaders/you-get/app/core/values.py, downloaders/you-get/app/core/webhook.py, downloaders/you-get/requirements.txt, hack/install_v2ray.sh, hack/install_youget.sh, kubespider/api/types.py, kubespider/core/kubespider_global.py, kubespider/download_provider/youget_download_provider/provider.py, kubespider/source_provider/bilibili_source_provider/provider.py
Fixes https://github.com/jwcesign/kubespider/issues/51
*
*
*
```release-note
```
=> Support bilibli video download with youget

kubespider/core/download_trigger.py, kubespider/download_provider/youget_download_provider/provider.py
Fixes #
*
*
*
```release-note
```
=> Fix you-get url support types

.config/source_provider.cfg, .github/workflows/kubespider-deploy-test.yaml, .pylintrc, downloaders/you-get/app/core/tasks.py, downloaders/you-get/app/core/values.py, downloaders/you-get/app/core/webhook.py, hack/install_youget.sh, kubespider/core/kubespider_global.py, kubespider/download_provider/youget_download_provider/provider.py, kubespider/source_provider/youtube_source_provider/provider.py
Fixes #none
* Print out the progress of you-get downloading
* Implement youtube source provider
```release-note
```
=> Print out the progress of you-get downloading&Implement youtube source provider

docs/zh/user_guide/api_docs/README.md, kubespider/core/download_trigger.py
Fixes #
*
*
*
```release-note
```
=> fix: when not match source provider, do not call the sub functions

.github/workflows/kubespider-acr-latest-build.yaml, .github/workflows/kubespider-dockerhub-latest-build.yaml
Part of #100 
* Fix latest images build failed
```release-note
```
=> Fix latest images build failed

.config/kubespider.yaml, kubespider/core/download_trigger.py, kubespider/source_provider/mikanani_source_provider/provider.py, kubespider/utils/helper.py
Fixes #none
* mikanani被墙了，支持设置代理
```release-note
```
=> Add proxy for source parse

docs/zh/user_guide/transmission_download_provider/README.md, kubespider/download_provider/transmission_download_provider/provider.py
- transmission下载种子文件时，应该传递种子文件内容。
- 更正 transmission 说明文档
=> fix(download_provider): transmission下载种子文件时，应该传递种子文件内容。

README-CN.md, README.md
Fixes #
* Update docs about configuration
```release-note
```
=> Update docs about configuration

chrome-extension/manifest.json, chrome-extension/service_worker.js
Fixes #none
* Add informer for download trigger.
```release-note
```
=> Add informer for download trigger

.config/kubespider.yaml, CHANGELOG/template.md, chrome-extension/manifest.json, setup.py
Fixes #
* Update some typo and add release template
*
*
```release-note
```
=> Update some typo and add release template

.config/pt_provider.yaml, kubespider/pt_provider/nexusphp_pt_provider/provider.py
Fixes #
*
*
*
```release-note
```
=> Fix bugs when pt provider disabled

.config/kubespider.yaml, .config/pt_provider.yaml, .github/workflows/kubespider-china-mainland-deploy-test.yaml, .gitignore, kubespider/pt_provider/nexusphp_pt_provider/provider.py
Fixes #
* Make pt provider yaml more concise
```release-note
```
=> Make pt provider yaml more concise

.config/source_provider.yaml, docs/zh/user_guide/general_rss_source_provider/README.md, kubespider/source_provider/general_rss_source_provider/provider.py
* 添加对种子文件格式支持
* 添加自定义正则表达式提取文件标题，完善下载路径
* 删除不必要字段
```release-note
NONE
```
=> feat: add torrent file type and custom title pattern support

Dockerfile, kubespider/core/kubespider.py, requirements.txt
* 根据flask警告添加WSGI服务
* 更新Dockerfile降低镜像大小 
```release-note
```
=> fix: decrease the size of docker image

.config/download_provider.yaml, docs/zh/user_guide/ytdlp_download_provider/README.md, downloaders/you-get/app/app.py, downloaders/you-get/app/core/tasks.py, downloaders/you-get/app/core/webhook.py, downloaders/yt-dlp/app/app.py, downloaders/yt-dlp/app/core/tasks.py, downloaders/yt-dlp/app/core/values.py, downloaders/yt-dlp/app/core/webhook.py, hack/install_ytdlp.sh, kubespider/download_provider/ytdlp_download_provider/provider.py
Fixes #128 
*
*
*
```release-note
```
=> feat: Support video format convertion for yt-dlp

.github/workflows/kubespider-acr-latest-build.yaml, .github/workflows/kubespider-dockerhub-latest-build.yaml, README-CN.md, downloaders/you-get/Dockerfile, downloaders/yt-dlp/Dockerfile
Fixes #none
* Add downloader image build workflow
```release-note
```
=> workflow: Add downloader image build workflow

.github/workflows/kubespider-acr-latest-build.yaml, .github/workflows/kubespider-dockerhub-latest-build.yaml
Fixes #
- fix the path configuration for building the yt-dlp image in workflow.
=> ci(workflow): fix yt-dlp build step

.config/kubespider.yaml, kubespider/api/types.py, kubespider/api/values.py, kubespider/core/kubespider.py, kubespider/core/kubespider_global.py, kubespider/core/period_server.py, kubespider/core/pt_server.py, kubespider/core/webhook_server.py, kubespider/utils/global_config.py, kubespider/utils/helper.py
Fixes #
* cleanup: Refactor the code about configuration.
*
*
```release-note
```
=> cleanup: Refactor the code about configuration

README-CN.md, README.md, docs/en/faq.md, docs/zh/faq.md
Fixes #
Add FAQ 
```release-note
```
=> doc: Add FAQ

.github/workflows/kubespider-release-notes.yaml, CHANGELOG/template.md, CONTRIBUTING-CN.md, CONTRIBUTING.md, README-CN.md, README.md, chrome-extension/js/kubespider.js, docs/en/faq.md, docs/en/user_guide/deploy_kubspider.md, docs/zh/faq.md, docs/zh/maintenance/cooperation/ask_for_cooperation.md, docs/zh/user_guide/jellyfin_install_config/README.md, docs/zh/user_guide/plex_install_config/README.md, docs/zh/user_guide/qbittorrent_download_provider/README.md, docs/zh/user_guide/thunder_install_config/README.md, docs/zh/user_guide/transmission_download_provider/README.md, docs/zh/user_guide/youget_download_provider/README.md, docs/zh/user_guide/ytdlp_download_provider/README.md, setup.py
Fixes #none
* clearnup: Update all the info to opennaslab related
```release-note
```
=> cleanup: Update all the info to opennaslab related

README-CN.md, README.md
Fixes #
*
*
*
```release-note
```
=> doc: Update readme

README.md, hack/install_kubespider.sh
Fixes #
*
*
*
```release-note
```
=> cleanup: Update install scripts

.config/source_provider.yaml, README-CN.md, README.md, docs/zh/user_guide/bilibili_source_provider/README.md, kubespider/core/webhook_server.py, kubespider/pt_provider/nexusphp_pt_provider/provider.py, kubespider/source_provider/magic_source_provider/provider.py, kubespider/source_provider/meijutt_source_provider/provider.py, kubespider/utils/helper.py
Fixes #
*
*
*
```release-note
```
=> feat: Make magic source provider more general

Dockerfile, kubespider/api/values.py, kubespider/core/config_handler.py, kubespider/core/runner.py
Fixes #none
* feat: Support config init when the files miss
```release-note
```
=> feat: Support config init when the files miss

Dockerfile, README-CN.md, README.md, docs/en/user_guide/installation/README.md, docs/zh/user_guide/installation/README.md
Fixes #
* Add docs to show how to deploy with docker-cli and docker-compose
=> Add doc for docker deployment

docs/zh/maintenance/cooperation/ask_for_cooperation.md, docs/zh/user_guide/aria2_download_provider/README.md, docs/zh/user_guide/bilibili_source_provider/README.md, docs/zh/user_guide/btbtt12_disposable_source_provider/README.md, docs/zh/user_guide/magic_source_provider/README.md, docs/zh/user_guide/meijutt_source_provider/README.md, docs/zh/user_guide/mikanani_source_provider/README.md, docs/zh/user_guide/qbittorrent_download_provider/README.md, docs/zh/user_guide/transmission_download_provider/README.md, docs/zh/user_guide/trigger_download/README.md, docs/zh/user_guide/youget_download_provider/README.md, docs/zh/user_guide/youtube_source_provider/README.md, docs/zh/user_guide/ytdlp_download_provider/README.md
Fixes #
*
*
*
```release-note
```
=> docs: fix image link

.config/kubespider.yaml, kubespider/core/download_trigger.py, kubespider/utils/global_config.py
Fixes #none
* feat: Disable auto change download provider
*
*
```release-note
```
=> feat: Disable auto change download provider

.github/workflows/kubespider-acr-latest-build.yaml, .github/workflows/kubespider-acr-release.yaml, .github/workflows/kubespider-china-mainland-deploy-test.yaml, .github/workflows/kubespider-deploy-test.yaml, .github/workflows/kubespider-dockerhub-latest-build.yaml, .github/workflows/kubespider-dockerhub-release.yaml, Dockerfile, entrypoint.sh
* Docker container add `PUID` `PGID` `UMASK` env
* Change the program running directory to `/kubespider`
```release-note
The mount directory is changed to `/kubespider/.config`
```
=> feat: docker add puid, pgid, umask settings

hack/install_youget.sh
Fixes #
*
*
*
```release-note
```
=> fix: change youget.sh mount path

.github/workflows/kubespider-dockerhub-latest-build.yaml, downloaders/you-get/Dockerfile, downloaders/you-get/app/core/webhook.py, downloaders/you-get/entrypoint.sh, downloaders/yt-dlp/Dockerfile, downloaders/yt-dlp/app/core/webhook.py, downloaders/yt-dlp/entrypoint.sh, hack/install_kubespider.sh, hack/install_youget.sh, hack/install_ytdlp.sh
tiktok-dlp我没看到action，就先不改了。
这些你先review一下吧
=> feat: refactor the you-get yt-dlp docker image

.github/workflows/kubespider-china-mainland-deploy-test.yaml, .github/workflows/kubespider-deploy-test.yaml, downloaders/you-get/Dockerfile, downloaders/yt-dlp/Dockerfile
Fixes #none
* fix: install ffmpeg in download container
*
*
```release-note
```
=> fix: install ffmpeg in download container

docs/zh/contribute/implement_source_provider_cn.md, downloaders/you-get/README.md
Fixes #
* doc: Updte docs
*
*
```release-note
```
=> doc: Updte docs

README-CN.md, README.md
Fixes #
*
*
*
```release-note
```
=> doc: Add invatation link in docs

docs/zh/user_guide/install_with_command/README.md
Fixes #
*
*
*
```release-note
```
=> doc: Update docker-compose.yaml example

downloaders/tiktok-dlp/Dockerfile, downloaders/tiktok-dlp/app/core/tasks.py, downloaders/tiktok-dlp/app/thirdparty/__init__.py, downloaders/tiktok-dlp/app/thirdparty/common/__init__.py, downloaders/tiktok-dlp/app/thirdparty/common/utils.py, downloaders/tiktok-dlp/app/thirdparty/douyin/__init__.py, downloaders/tiktok-dlp/app/thirdparty/douyin/database.py, downloaders/tiktok-dlp/app/thirdparty/douyin/douyin.py, downloaders/tiktok-dlp/app/thirdparty/douyin/douyinapi.py, downloaders/tiktok-dlp/app/thirdparty/douyin/download.py, downloaders/tiktok-dlp/app/thirdparty/douyin/result.py, downloaders/tiktok-dlp/app/thirdparty/douyin/urls.py, downloaders/tiktok-dlp/requirements.txt
Fixes #none
*
*
*
```release-note
```
=> feat: Put downloader into third party

kubespider/source_provider/bilibili_source_provider/provider.py, kubespider/source_provider/btbtt12_disposable_source_provider/provider.py, kubespider/source_provider/general_rss_source_provider/provider.py, kubespider/source_provider/magic_source_provider/provider.py, kubespider/source_provider/meijutt_source_provider/provider.py, kubespider/source_provider/mikanani_source_provider/provider.py, kubespider/source_provider/tiktok_source_provider/provider.py, kubespider/source_provider/youtube_source_provider/provider.py
Fixes #
*
*
*
```release-note
```
=> fix: get provider as list if possible

kubespider/core/config_handler.py
Fixes #
*
*
*
```release-note
```
=> fix: Fix config gets empty

.config/download_provider.yaml, Dockerfile, kubespider/api/values.py, kubespider/core/config_handler.py
- Dockerfile: Add /.dockerenv file
- kubespider/api/values.py: Add DEPENDENCIES_CONFIG to Config enum
- kubespider/core/config_handler.py: Copy DEPENDENCIES_CONFIG if it exists
Fixes #231 #222
=> feat: Copy DEPENDENCIES_CONFIG if it exists

kubespider/core/download_trigger.py, kubespider/utils/helper.py
add download trigger retry mechanism
#227
=> feat：add download trigger retry mechanism

.github/workflows/kubespider-deploy-test.yaml, hack/test/deploy_test.sh
Fixes #
*
*
*
```release-note
```
=> clean: extract deploy test process as a script

README-CN.md, README.md
Fixes #
*
*
*
```release-note
```
=> doc: Add douyin related docs

.config/kubespider.yaml, .config/pt_provider.yaml, kubespider/core/kubespider_controller.py, kubespider/core/pt_server.py, kubespider/pt_provider/nexusphp_pt_provider/provider.py, kubespider/pt_provider/provider.py
Fixes #
*
*
*
```release-note
```
=> feat: Make PT provider more generic

kubespider/core/pt_server.py, kubespider/pt_provider/nexusphp_pt_provider/provider.py
Fixes #
*
*
*
```release-note
```
=> cleanup: Add logs about skip downloading

docs/zh/user_guide/ytdlp_download_provider/README.md
Fixes #
*
*
*
```release-note
```
=> doc: fix describe

hack/install_kubespider.sh
=> feat:适配macos环境下docker部署脚本

CONTRIBUTING-CN.md, Dockerfile, docker-compose.yml, downloaders/yt-dlp/Dockerfile, downloaders/yt-dlp/docker-compose.yml, downloaders/yt-dlp/entrypoint.sh, downloaders/yt-dlp/requirements.txt, entrypoint.sh
https://github.com/opennaslab/kubespider/pull/251#issue-1793890146
合并 commit 后的
=> cli: support code  hot reload for development

kubespider/core/pt_server.py
Fixes #
*
*
*
```release-note
```
=> fix: fix pt download size calculation

docs/zh/user_guide/magic_source_provider/README.md
Fixes #
*
*
*
```release-note
```
=> doc: add majic source provider extension config

README-CN.md, README.md
Fixes #
*
*
*
```release-note
```
=> doc: update group invitation link

docs/zh/roadmap.md
Fixes #
*
*
*
```release-note
```
=> doc: update roadmap

hack/install_kubespider.sh
Fixes #266 
*
*
*
```release-note
```
=> fix: create .config dir by default

.github/ISSUE_TEMPLATE/bug.md
Fixes #
*
*
*
```release-note
```
=> Add bug template for issue

hack/install_jellyfin.sh
Fixes #
*
*
*
```release-note
```
=> feat: fix jellyfin mount

kubespider/app.py, setup.py
Fixes #
*
*
*
```release-note
```
=> feat: add python version check

README.md
Fixes #
*
*
*
```release-note
```
=> feat: fix typo

docs/zh/user_guide/asustor_installation/README.md
Fixes #
*
*
*
```release-note
```
=> doc: update docs

.github/workflows/kubespider-image-sync.yaml
Fixes #278 
```release-note
Dockerhub sync multi-platform image
```
=> ci: Dockerhub sync multi-platform image

.config/source_provider.yaml, CONTRIBUTING-CN.md, kubespider/core/config_handler.py, kubespider/download_provider/qbittorrent_download_provider/provider.py, kubespider/download_provider/transmission_download_provider/provider.py, kubespider/source_provider/bilibili_vlogger_subscribe_source_provider/provider.py
Fixes #
*
*
*
```release-note
```
=> feat: add bilibili vlogger subscriber source provider

.config/notification_provider.yaml
Fixes #
*
*
*
```release-note
```
=> fix: disable pushdeer by default

.config/notification_provider.yaml, docs/zh/user_guide/pushdeer_provider/README.MD, kubespider/core/config_handler.py, kubespider/core/notification_server.py, kubespider/core/period_server.py, kubespider/core/webhook_server.py, kubespider/notification_provider/provider.py, kubespider/notification_provider/pushdeer_provider/provider.py, kubespider/notification_provider/telegram_provider/provider.py
Fixes #
* optimize notification
* add telegram provider
```release-note
```
=> feat: Add Telegram as a notification provider

kubespider/core/webhook_server.py
Fixes #
*
*
*
```release-note
```
=> feat: notify webhook users if there is no links

docs/zh/user_guide/pushdeer_notification_provider/README.md, docs/zh/user_guide/telegram_notification_provider/README.md, kubespider/core/webhook_server.py
Fixes #
*
*
*
```release-note
```
=> cleanup: delete redudent checking

README.md, kubespider/core/period_server.py, kubespider/download_provider/tiktok_dlp_download_provider/provider.py, kubespider/download_provider/xunlei_download_provider/provider.py, kubespider/download_provider/youget_download_provider/provider.py, kubespider/download_provider/ytdlp_download_provider/provider.py, kubespider/notification_provider/telegram_notification_provider/provider.py, kubespider/utils/helper.py
Fixes #294 
*
*
*
```release-note
```
=> fix: remove proxy when calling download provider

docs/zh/user_guide/thunder_install_config/README.md
Fixes #
*
*
*
```release-note
```
=> doc: 更新迅雷下载配置文档

docs/zh/user_guide/thunder_install_config/README.md
Fixes #
*
*
*
```release-note
```
=> doc: fix typo

kubespider/utils/helper.py
Fixes #
*
*
*
```release-note
```
=> fix: fix cookie parse

kubespider/utils/helper.py
Fixes #
*
*
*
```release-note
```
=> fix: guess link type without download content

hack/install_kubespider.sh, hack/install_transmission_pt.sh
Fixes #
*
*
*
```release-note
```
=> cleanup: make scripts better

kubespider/api/values.py, kubespider/core/config_handler.py, kubespider/core/download_trigger.py, kubespider/core/kubespider_controller.py, kubespider/core/period_server.py, kubespider/core/pt_server.py, kubespider/core/runner.py, kubespider/core/source_manager.py, kubespider/core/webhook_server.py, kubespider/download_provider/aria2_download_provider/provider.py, kubespider/download_provider/provider.py, kubespider/download_provider/qbittorrent_download_provider/provider.py, kubespider/download_provider/tiktok_dlp_download_provider/provider.py, kubespider/download_provider/transmission_download_provider/provider.py, kubespider/download_provider/xunlei_download_provider/provider.py, kubespider/download_provider/youget_download_provider/provider.py, kubespider/download_provider/ytdlp_download_provider/provider.py, kubespider/source_provider/alist_source_provider/provider.py, kubespider/source_provider/bilibili_source_provider/provider.py, kubespider/source_provider/bilibili_vlogger_subscribe_source_provider/provider.py, kubespider/source_provider/btbtt12_disposable_source_provider/provider.py, kubespider/source_provider/general_rss_source_provider/provider.py, kubespider/source_provider/magic_source_provider/provider.py, kubespider/source_provider/meijutt_source_provider/provider.py, kubespider/source_provider/mikanani_source_provider/provider.py, kubespider/source_provider/provider.py, kubespider/source_provider/tiktok_source_provider/provider.py, kubespider/source_provider/youtube_source_provider/provider.py, kubespider/test/source_provider/test_mikanani_source_provider.py, kubespider/utils/helper.py
```release-note
- Define data models
- Support passing extension parameters from webhook and sending to source_provider
```
=> refactor: Define data models

README-CN.md, README.md, kubespider/api/values.py, kubespider/core/download_trigger.py, kubespider/core/kubespider_controller.py, kubespider/core/source_manager.py, kubespider/core/webhook_server.py, kubespider/source_provider/magic_source_provider/provider.py
Fixes #
*
*
*
```release-note
```
=> fix: fix bugs about webhook trigger

kubespider/core/period_server.py, kubespider/core/source_manager.py, kubespider/source_provider/magic_source_provider/provider.py
Fixes #
*
*
*
```release-note
```
=> fix: fix download path

kubespider/core/source_manager.py, kubespider/utils/helper.py
Fixes #
*
*
*
```release-note
```
=> feat: add redirect file type checking

kubespider/core/pt_server.py, kubespider/download_provider/transmission_download_provider/provider.py, kubespider/pt_provider/nexusphp_pt_provider/provider.py
Fixes #
*
*
*
```release-note
```
=> feat: add multi-thread support for pt server

kubespider/notification_provider/bark_notification_provider/provider.py
Fixes #
*
*
*
```release-note
```
=> fix: bark provider pylint error

kubespider/core/pt_server.py
Fixes #313 
*
*
*
```release-note
```
=> fix: fix unexpected seeding task deletion

docs/zh/user_guide/install_with_command/README.md
从 root/.config 切换为 app/.config
Fixes #
*
*
*
```release-note
```
=> doc: 修改 docker 部署命令中 volume 地址

kubespider/pt_provider/nexusphp_pt_provider/provider.py
Fixes #324 
*
*
*
```release-note
```
=> fix: delete seeding task before configuration

README-CN.md, README.md
Fixes #
*
*
*
```release-note
```
=> doc: add ugreen installation guide in readme

downloaders/you-get/app/core/tasks.py
Fixes #
*
*
*
```release-note
```
=> fix: add default cookie path

docs/zh/user_guide/magic_source_provider/README.md
Fixes #
*
*
*
```release-note
```
=> doc: add link selector configuration

Dockerfile, kubespider/download_provider/xunlei_download_provider/provider.py, requirements.txt
Fixes #339 
* use bencodepy instead of libtorrent
* upgrade python to 3.11
=> feat: upgrade Python to 3.11

README-CN.md, README.md
Fixes #
*
*
*
```release-note
```
=> doc: updat python version in readme

kubespider/source_provider/meijutt_source_provider/provider.py
Fixes #351
*
*
*
```release-note
```
=> fix: fix meijutt tv download

kubespider/core/source_manager.py
```release-note
- Pass download_param to the link structure not event.
```
=> fix: Pass download_param to the link structure.

.config/download_provider.yaml, docs/zh/user_guide/qbittorrent_download_provider/README.md, kubespider/download_provider/qbittorrent_download_provider/provider.py
Fixes #
*
*
*
```release-note
```
=> feat: Support qbittorrent to use category as download path

kubespider/source_provider/youtube_source_provider/provider.py
Fixes # YouTube has some other hostname, add these
=> add some youtube host judgement

.config/download_provider.yaml, .github/workflows/kubespider-deploy-test.yaml, .github/workflows/kubespider-latest-build.yaml, .github/workflows/kubespider-release.yaml
Fixes #none
* ci: add linux/arm64 image build test
```release-note
```
=> ci: add linux/arm64 image build test

.github/workflows/kubespider-latest-build.yaml, .github/workflows/kubespider-release.yaml, downloaders/yt-dlp/Dockerfile, downloaders/yt-dlp/requirements.txt
Fixes #none
* ci: udgarde python lib dep and upgrade workflow dep
```release-note
```
=> ci: udgarde python lib dep and upgrade workflow dep

.github/workflows/kubespider-latest-build.yaml, .github/workflows/kubespider-release.yaml
Fixes #none
* ci: disable arm64 image build for acr
```release-note
```
=> ci: disable arm64 image build for acr

kubespider/source_provider/meijutt_source_provider/provider.py
feat: meijutt_source_provider filter link type & auto choose correct link type
一些较老的美剧 在第一个tab处都是 ed2k链接 例如：https://www.meijutt.tw/content/meiju162.html
meijutt_source_provider 只会解析第一个tab，如果链接类型与LINK_TYPE_MAGNET不一致则会跳过下载
本次commit改进了这一做法，meijutt_source_provider 会解析每一个tab，并且只下载第一个 链接类型与LINK_TYPE_MAGNET匹配的tab。
=> feat: meijutt_source_provider filter link type & auto choose correct link type

.config/download_provider.yaml, .github/workflows/kubespider-latest-build.yaml, kubespider/core/config_handler.py, kubespider/download_provider/yutto_download_provider/provider.py, kubespider/source_provider/bilibili_source_provider/provider.py, kubespider/source_provider/bilibili_vlogger_subscribe_source_provider/provider.py
=> feat: support yutto download provider

.github/workflows/kubespider-extension-build.yaml
```release-note
- new workflow to build chrome-extension on kubespider-extension update.
```
=> new workflow to build chrome-extension on kubespider-extension update.

docs/zh/faq.md
Fixes #
* 增加 FAQ：更新使用 docker 安装的 kubespider 版本
* 增加 FAQ：更新 .config/xxx_provider.yaml 配置未生效
=> Update faq.md add two situations

.github/workflows/kubespider-deploy-test.yaml, .github/workflows/kubespider-latest-build.yaml, .github/workflows/kubespider-release.yaml, Dockerfile, kubespider/app.py
```release-note
- print logo and build commit hash when start.
```
=> feat: print logo and build commit hash when start.

.github/workflows/release-extension.yaml
```release-note
- upload chrome-extension.zip on release published
```
=> ci: upload chrome-extension.zip on release published

docs/zh/user_guide/mikanani_source_provider/README.md
Fixes [#452](https://github.com/opennaslab/kubespider/issues/452)
=> Update mikanani README.md

kubespider/api/values.py, kubespider/core/period_server.py, kubespider/source_provider/alist_source_provider/provider.py
=> fix: fix alist download bug(#456)

.config/kubespider.yaml, kubespider/core/runner.py, kubespider/core/telegram_server.py, kubespider/utils/global_config.py, kubespider/utils/helper.py, requirements.txt
add send to telegram bot , trigger download
```release-note
```
=> Feat add telegram bot

.config/kubespider.yaml, kubespider/core/telegram_server.py, kubespider/utils/helper.py
Fixes #none
* fix: fix telegram downloading trigger
```release-note
`kubespider-core`: fix telegram downloading trigger
```
=> fix: fix telegram downloading trigger

kubespider/core/telegram_server.py
Fixes #none
* keep the original url received
```release-note
```
=> fix: keep the original url received

kubespider/api/v2/plugin/views.py, kubespider/core/plugin_manager.py
* Add "[DELETE] /api/v2/plugin/<plugin_name>" api
* Add "[UPDATE] /api/v2/plugin/<plugin_name>" api
=> feat(api): add delete and update methods for plugin apiv2

kubespider/core/plugin_binding.py
Fixes #none
* fix: fix instance config updating error
```release-note
```
=> fix: fix instance config updating error

docs/zh/user_guide/ani_source_provider/README.md
Fixes #none
* doc: update doc
```release-note
```
=> doc: update doc

kubespider/api/v2/plugin/views.py, kubespider/core/plugin_manager.py, sdk/example/Dockerfile
Fixes #
*
*
*
```release-note
- Add up status to plugin api
```
=> feat: plugin api add up status

kubespider/source_provider/bilibili_source_provider/provider.py
Fixes #
*
*
*
```release-note
```
=> add bilibili short url support

docs/zh/contribute/plugin_definition.md
Fixes #
*
*
*
```release-note
```
=> update:update plugin definition

kubespider/api/values.py, kubespider/source_provider/ani_source_provider/provider.py
Fixes #none
* fix: fix the occasional pylint error
```release-note
```
=> fix: fix the occasional pylint error

README-CN.md, README.md
doc: update main readme guide with unraid installation
=> doc: update main readme guide with unraid installation

docs/zh/user_guide/magic_source_provider/README.md
Fixes #none
* doc: make majic source provider guidance better
```release-note
```
=> doc: make majic source provider guidance better

kubespider/source_provider/bilibili_source_provider/provider.py
Fixes #489 
```release-note
- Added check for existence of URLs in event source
```
=> fix: Added check for existence of URLs in event source

kubespider-extension/src/background/index.ts
Fixes #475 
```release-note
- Improve dataSource retrieval logic, first try to get selected text, then link URL, finally tab URL
```
=> feat: Improve dataSource retrieval logic

docs/zh/contribute/plugin_definition.md, kubespider/api/v2/notification/views.py, kubespider/api/v2/plugin/views.py, kubespider/core/notification_manager.py, kubespider/core/plugin_binding.py, kubespider/core/plugin_manager.py, kubespider/notification_provider/__init__.py, kubespider/notification_provider/provider.py, kubespider/notification_provider/synology_notification_provider/provider.py, kubespider/utils/definition.py, kubespider/utils/types.py
Fixes #
*
*
*
```release-note
```
=> feat:unified standard definition

kubespider/utils/version_parser.py
=> fix(utils): wrong version checker

kubespider/source_provider/btbtt12_disposable_source_provider/provider.py
Fixes #
*
*
*
```release-note
```
=> fix: fix domain name match with btbtt12

docs/zh/maintenance/release/README.md
Fixes #
*
*
*
```release-note
```
=> doc: add version release doc

kubespider/api/values.py, kubespider/download_provider/xunlei_download_provider/provider.py
Fixes #
*
*
*
```release-note
```
=> fix: fix xunlei download

.github/FUNDING.yml
Fixes #none
*
*
*
```release-note
```
=> cleanup: delete unnecessary things

kubespider/api/values.py, kubespider/source_provider/btbtt12_disposable_source_provider/provider.py, kubespider/source_provider/magic_source_provider/provider.py, kubespider/source_provider/youtube_source_provider/provider.py
Fixes #539 
the url may not be a valid url
=> fix: Issue #539, the url may not be a valid url

docs/en/user_guide/install_with_command/README.md, docs/zh/user_guide/install_with_command/README.md
Fixes docker-compose error, depend services name error can't work 
* update README.md
=> fix: fix docker-compose depend services name error

.github/workflows/kubespider-extension-build.yaml, kubespider-extension/package-lock.json, kubespider-extension/package.json
Fixes #552 #548 
*
*
*
```release-note
```
=> Fix CSP issuse on Chrome 130+
