opennaslab/kubespider

- .config/download_provider.cfg
- .pylintrc
- hack/install_qbittorrent.sh
- kubespider/core/kubespider_global.py
- kubespider/download_provider/qbittorrent_download_provider/provider.py
- requirements.txt
Fix #56 
- Add qbittorrent download provider
- Add qbittorrent config into download_provider.cfg
- Add a docker based qbittorrent script for newer
**Due to the fact that qbittorrent only supports torrent or magnet link, this provider doesn't support general link download**
> feat: add qbittorrent download provider support

- .config/download_provider.yaml
- .config/source_provider.yaml
- .config/state.yaml
- docs/zh/user_guide/aria2_download_provider/README.md
- docs/zh/user_guide/bilibili_source_provider/README.md
- docs/zh/user_guide/btbtt12_disposable_source_provider/README.md
- docs/zh/user_guide/meijutt_source_provider/README.md
- docs/zh/user_guide/mikanani_source_provider/README.md
- docs/zh/user_guide/qbittorrent_download_provider/README.md
- docs/zh/user_guide/thunder_install_config/README.md
- docs/zh/user_guide/youget_download_provider/README.md
- kubespider/core/download_trigger.py
- kubespider/core/kubespider_global.py
- kubespider/core/period_server.py
- kubespider/core/webhook_server.py
- kubespider/download_provider/aria2_download_provider/provider.py
- kubespider/download_provider/provider.py
- kubespider/download_provider/qbittorrent_download_provider/provider.py
- kubespider/download_provider/xunlei_download_provider/provider.py
- kubespider/download_provider/youget_download_provider/provider.py
- kubespider/source_provider/bilibili_source_provider/provider.py
- kubespider/source_provider/btbtt12_disposable_source_provider/provider.py
- kubespider/source_provider/meijutt_source_provider/provider.py
- kubespider/source_provider/mikanani_source_provider/provider.py
- kubespider/source_provider/provider.py
- kubespider/source_provider/youtube_source_provider/provider.py
Close #79 
* 支持多个下载器、订阅源，名字可以自由配置，使用`type`指定下载器类型
* 订阅源可以按名字指定使用的下载器
* 订阅源可以自定义下载参数，传递给下载器使用；具体含义将由下载器定义（目前仅qBittorrent支持下载参数）
* 按以上改动更新了一波readme
个人仅有mikan+qb+aria的下载环境，其他配置需要众测一下。
> 支持同类型的多个下载器、订阅源，支持订阅源指定下载器

- kubespider/core/webhook_server.py
- kubespider/source_provider/meijutt_source_provider/provider.py
- kubespider/utils/helper.py
- `kubespider/source_provider/meijutt_source_provider/provider.py` 检查mjtt获取的下载链接类型是否符合provider.link_type。
- `get_link_type ` 获取链接类型时，增加根据rfc6266从headers中获取filename并检查类型是否为torrent。
> fix&feat: 修正mjtt获取下载链接不一定是magent。增强get_link_type获取链接类型。

- kubespider/core/kubespider_global.py
- kubespider/core/period_server.py
- kubespider/download_provider/aria2_download_provider/provider.py
- kubespider/download_provider/provider.py
- kubespider/download_provider/qbittorrent_download_provider/provider.py
- kubespider/download_provider/transmission_download_provider/provider.py
- kubespider/download_provider/xunlei_download_provider/provider.py
- kubespider/download_provider/youget_download_provider/provider.py
- kubespider/download_provider/ytdlp_download_provider/provider.py
- kubespider/source_provider/bilibili_source_provider/provider.py
- kubespider/source_provider/btbtt12_disposable_source_provider/provider.py
- kubespider/source_provider/general_rss_source_provider/provider.py
- kubespider/source_provider/meijutt_source_provider/provider.py
- kubespider/source_provider/mikanani_source_provider/provider.py
- kubespider/source_provider/provider.py
- kubespider/source_provider/youtube_source_provider/provider.py
- kubespider/test/source_provider/test_mikanani_source_provider.py
- kubespider/test/utils/test_config.yaml
- kubespider/test/utils/test_config_reader.py
- kubespider/utils/config_reader.py
- kubespider/utils/helper.py
将配置读取的逻辑做了抽象，支持给订阅源、下载器和全局设置项注入不同形式的配置读取方式。
在这个能力之上，以后可以更方便实现配置文件拆分，例如`.config/source_provider`下的所有yaml都可以认作订阅源配置，方便mikan源订阅过滤规则太多进行管理。
注入配置可以让`downloader_provider`、`source_provider`自身的代码更加可测，例如可以使用单元测试验证任何一个配置项的存在与否的表现。
后续能做的事情：进行拆分`downloader_provider`、`source_provider`内部逻辑，例如将`mikanani_provider`中访问网页获取标题、`qbittorrent_provider`中实际与qb交互的代理对象也进行注入，就能完全针对里面的代码逻辑进行单元测试了。
> 能做不代表是我做
> 后面精力问题，我不会花很多时间在这里，考虑一下T了我的权限？
> 配置读取改成注入形式

- kubespider/source_provider/general_rss_source_provider/provider.py
* 修复general_rss_source_provider中文件类型和链接类型错误的bug
```release-note
```
> fix: wrong file type and link type in general_rss_source_provider

- kubespider/core/config_handler.py
- kubespider/core/kubespider_controller.py
- kubespider/core/runner.py
- kubespider.yaml file exits check add config_path()
- move "while true" after the startup of the webhook_server
Fixes #175
> fix: Startup process issues

- kubespider/download_provider/transmission_download_provider/provider.py
- kubespider/source_provider/bilibili_source_provider/provider.py
- kubespider/source_provider/general_rss_source_provider/provider.py
- kubespider/source_provider/magic_source_provider/provider.py
- kubespider/source_provider/meijutt_source_provider/provider.py
- kubespider/source_provider/mikanani_source_provider/provider.py
- kubespider/source_provider/tiktok_source_provider/provider.py
- kubespider/source_provider/youtube_source_provider/provider.py
- kubespider/test/source_provider/test_mikanani_source_provider.py
Fixes #
When obtaining download providers, we should return a list instead of a string. If one source provider configures the download provider as `abc`, and there are `ab` and `bc` providers available, it will match them, but this is not the expected behavior.
```release-note
```
> fix: Fix getting download providers' name list

- kubespider/core/download_trigger.py
- kubespider/core/pt_server.py
Fixes #none
- The constructor parameter for `KubespiderDownloader` should be of type list.
- Set a default value for the `seeding_time` field in the `PTServer`.
> fix: KubespiderDownloader.__init__ param type

- chrome-extension/js/kubespider.js
- chrome-extension/kubespider.html
- chrome-extension/manifest.json
- chrome-extension/service_worker.js
Fixes #none
- chrome ext send task，both send tab.url cookies.
- Temporarily hidden by default, after release when api stable.
> feat: chrome-ext trigger download support capture cookies.

- kubespider/core/source_manager.py
- kubespider/source_provider/magic_source_provider/provider.py
- kubespider/utils/helper.py
Fixes #
* kubespider-extension send tab cookies use 'cookies'.
> fix: webhook trigger extra param key 'cookies'

- docs/zh/user_guide/tiktok_download_provider/README.md
- kubespider/core/source_manager.py
Fixes #
- When source_provider is not matched, the path is not correctly concatenated with the file_type prefix.
- Replace the shortcut link, make the path configuration more clear
> fix: Issue with path when source_provider is not matched

- .github/workflows/release-extension.yaml
fixes: https://github.com/opennaslab/kubespider/issues/325
How to use: 
- Create a tag with prefix `extension-v`, e.g. `extesion-v0.2.0`
see demo: https://github.com/zirain/kubespider/actions/runs/6064872582 and https://github.com/zirain/kubespider/actions/runs/6064872582
Best Practices:
keep tag suffix same with `manifest.json`
> init Release Chrome Extension action

- kubespider/source_provider/btbtt12_disposable_source_provider/provider.py
修复通过浏览器插件向kubespider发送btbtt12的下载链接可能不能正常下载的情况
Fixes https://github.com/opennaslab/kubespider/issues/336
*
*
*
```release-note
```
> fix: fix btbtt12 downloading

- .config/download_provider.yaml
- kubespider/download_provider/ytdlp_download_provider/provider.py
Currently, these configurations are scattered in various places, and later, there is consideration to optimize and consolidate the configuration of YouTube’s URLs.
> simply download youtube by default config

- downloaders/yt-dlp/entrypoint.sh
- yt-dlp cannot be started by non-root users
> fix: yt-dlp cannot be started by non-root users

- .config/kubespider.yaml
- kubespider/app.py
- kubespider/core/api/__init__.py
- kubespider/core/api/v2/source_provider/views.py
- kubespider/core/middleware/source_provider/sdk_source_provider/provider.py
- kubespider/core/runner.py
- kubespider/utils/config_reader.py
- kubespider/utils/global_config.py
- kubespider/utils/helper.py
- kubespider/utils/values.py
- Modify the configuratiuon file read policy
Now, KubeSpider will check whether the configuration file exists. If it does not exist, it will automatically create a default configuration file in the specified directory and run it. The specified directory can be specified through the environment variable `KUBESPIDER_HOME`. The default path is `/data/kubespider`
For local developer, there is no need to conflict with the original system `HOME` env var.
```
KUBESPIDER_HOME=$HOME/.config/kubespider python kubespider/app.py
```
Subsequent sqlite files and source_provider bins will be uniformly saved in the KUBESPIDER_HOME directory.
```
❯ tree $KUBESPIDER_HOME
/root/.config/kubespider
├── kubespider.db
├── kubespider.yaml
└── providers
└── source_bin
└── mikanani_provider
3 directories, 3 file …
```
> refactor(ui/config): Modify the configuration file read policy

- downloaders/yutto/requirements.txt
* bump yutto to 2.0.0-beta.33, see https://github.com/yutto-dev/yutto/releases/tag/v2.0.0-beta.32 and https://github.com/yutto-dev/yutto/releases/tag/v2.0.0-beta.33
```release-note
- bump yutto to `2.0.0-beta.33`
```
> chore: bump yutto to `2.0.0-beta.33`

- kubespider/core/plugin_manager.py
Fixes #none
* fix: do not raise error when re-enable plugin/can't delete plugin if there are config instances exist
```release-note
```
> fix: do not raise error when re-enable plugin/can't delete plugin if there are config instances exist

- docs/zh/contribute/plugin_definition.md
Fixes #472 
* doc: add plugin yaml definition
```release-note
```
> doc: add plugin yaml definition

- kubespider/download_provider/yutto_download_provider/provider.py
- kubespider/source_provider/bilibili_source_provider/provider.py
fix: yutto downloader does not recognize url pasted/shared from mobile app
```release-note
fix: yutto downloader does not recognize url pasted/shared from mobile app
```
> fix: yutto downloader not recognize url from app

- downloaders/yutto/app/core/tasks.py
fix: yutto downloader docker image does not read sessdata config under short link
```release-notes
fix: yutto downloader docker image does not read sessdata config under short link.
```
> fix: yutto downloader docker image does not read sessdata config under short link

- downloaders/yutto/app/core/tasks.py
- downloaders/yutto/requirements.txt
* bump yutto version to `2.0.0-beta.37`, see more details in:
- https://github.com/yutto-dev/yutto/releases/tag/v2.0.0-beta.34
- https://github.com/yutto-dev/yutto/releases/tag/v2.0.0-beta.35
- https://github.com/yutto-dev/yutto/releases/tag/v2.0.0-beta.36
- https://github.com/yutto-dev/yutto/releases/tag/v2.0.0-beta.37
* replace `YouGetTasks` with `YuttoTasks` in yutto downloader
```release-note
- bump yutto version to `2.0.0-beta.37`
```
> chore: bump yutto version to `2.0.0-beta.37` and fix typo in code

- .github/workflows/release-extension.yaml
- kubespider-extension/.env.chrome
- kubespider-extension/.env.firefox
- kubespider-extension/package-lock.json
- kubespider-extension/package.json
- kubespider-extension/src/lib/bridge/index.ts
- kubespider-extension/src/lib/storage/index.ts
- kubespider-extension/src/manifest.ts
- kubespider-extension/tsconfig.node.json
- kubespider-extension/vite.config.ts
- kubespider/core/webhook_server.py
- requirements.txt
Fixes #501 
```release-note
- kubespider-extension support firefox.
```
> feat: kubespider-extension support firefox.

- kubespider/source_provider/ani_source_provider/provider.py
Calling aria2 to download a link from the ANi API using the domain name `resources.ani.rip` has a high probability of being intercepted by its Cloudflare security mechanism and returning a 12kb TOS video, so replace the domain name of the download link with the real resolved `cloud.ani-download.workers.dev`
> Bypass Cloudflare TOS

- kubespider/source_provider/ani_source_provider/provider.py
在前几天的运行过程中发现有部分下载任务落盘的文件不带后缀名，但是Season 2以上的文件不受此影响。
查阅源码后发现，Season 2以上的文件名，是我通过解析器处理xml的title得到，但Season 1只是单纯的发送下载链接，其它事情交由download provider和服务器自行协商。
询问API管理员，收到的答复称该现象无法避免，因此在代码中给Season 1也强制指定了文件名
> Fix: 强制指定文件名，以避免服务器返回无后缀filename
